name: 'robles Publish [STAGING]'
on:
  push:
    branches:
      - 'editions/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint book
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint via robles
        uses: docker://razeware/robles:staging
        with:
          entrypoint: '/app/robles/bin/robles'
          args: 'book lint'
        env:
          ENV: staging
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify slack - test results
        uses: voxmedia/github-action-slack-notify-build@v1
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel: robles
          status: FAILED
          color: danger

  publish:
    name: Publish to alexandria
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Publish via robles
        uses: docker://razeware/robles:staging
        with:
          entrypoint: '/app/robles/bin/robles'
          args: 'book publish'
        env:
          ALEXANDRIA_BASE_URL: https://alexandria.rwdev.io:8443
          ALEXANDRIA_SERVICE_API_TOKEN: ${{ secrets.ALEXANDRIA_SERVICE_API_TOKEN_STAGING }}
          ENV: staging
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          AWS_BUCKET_NAME: robles-staging
          AWS_REGION: us-east-1
          IMAGES_CDN_HOST: assets.alexandria.rwdev.io
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

